server:
  port:8098
spring:
  application:
    name:service-gateway
  cloud:
    gateway:
      discovery:
      locator:
        enabled:true
        lower-case-service-id:true
    consul:
      host:106.54.140.164
      port:8500
